/** Define ids for each page. */
export const PAGE_IDS = {
  HOME: 'home',
  VIEW_BILLS: 'view-bills',
  VIEW_BILL: 'view-bill',
  ASSIGN_BILL: 'assign-bill',
  ADD_STUFF: 'add-stuff',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SEND_HEARING_NOTICE: 'send-hearing-notice',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  EDIT_ACCOUNT: 'edit-account',
  PROFILE: 'profile',
  SUBMIT_TESTIMONY: 'submit-testimony',
  CALENDAR: 'calendar',
  MANAGE_ACCOUNTS: 'manage-accounts',
  VIEW_HEARINGS: 'view-hearings',
  EDIT_TESTIMONY: 'edit-testimony',
  LIST_TESTIMONY: 'list-testimony',
  ADMIN_CREATE: 'admin-create',
};
