export const viewBill = {
  billlink: "www.google.com",
  billno: "HB 012E",
  office: ["OSIP", "OPS", "OCID", "ABCD", "EFGH", "HIJK"],
  action: "Testimony",
  status: "3rd Crossover",
  actno: 10,
  companion: "placeholder for companion",
  reporttitle: "Placeholder for report title",
  legtype: "Bill",
  committeereferral: ["com1", "com2", "com3"],
  measuretitle: "Placeholder for measure title",
  introducedby: "ABCDEFGHI",
  introducedbydate: "Wed Sep 21 2022",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  allversion: ["www.google.com", "www.youtube.com", "www.yahoo.com"],
  committeereports: ["www.google.com", "www.youtube.com", "www.yahoo.com"],
  hearingnotices: ["www.google.com", "www.youtube.com", "www.yahoo.com"],
  laststatus: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
  ],
  notifiedhearingdate: "Wed Sep 21 2022",
  notifiedhearing: "www.google.com",
  hearingdate: "Wed Sep 21 2022",
  hearingtime: "02:30 PM",
  hearinglocation: "Cabinet Building",
  committee: "Senate",
  type: "Decision Making",
  testifiercontact: ["abc@gmail.com", "def@gmail.com"],
  similar: [
    "orasdasem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
    "orem ipsdsdsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
  ],
  leadofficeposition: "What goes here?",
  testifier: "Cara Tanimura",
  approvedtestimony: ["abcdefghi.pdf", "abcdefghi.pdf", "abcdefghi.pdf"],
  monitoringreports: "what goes here?",
  hearingcomments: ["Comment 1", "Comment 2", "Comment 3"],
  testimony: [
    "orem ipsasdasasddum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
    "orem ipsasdaasdsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet",
  ],
  rationale:
    "orem ipsum dolasdor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
};
