export const viewBill = {
  billLink: 'www.google.com',
  billNo: 'HB-012E',
  office: ['OSIP', 'OPS', 'OCID', 'ABCD', 'EFGH', 'HIJK'],
  action: 'Testimony',
  status: '3rd Crossover',
  actionNumber: 10,
  companion: 'placeholder for companion',
  reportTitle: 'Placeholder for report title',
  legalType: 'Bill',
  committeeReferral: ['com1', 'com2', 'com3'],
  measureTitle: 'Placeholder for measure title',
  introducedBy: 'ABCDEFGHI',
  introducedByDate: 'Wed Sep 21 2022',
  description:
    'Lorem ipsum dolor sdsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  allVersions: ['www.google.com', 'www.youtube.com', 'www.yahoo.com'],
  committeeReports: ['www.google.com', 'www.youtube.com', 'www.yahoo.com'],
  hearingNotices: ['www.google.com', 'www.youtube.com', 'www.yahoo.com'],
  lastStatus: [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet',
    'Lorem ipsum dolsdor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet',
    'Lorem ipsum dasolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet',
  ],
  notifiedHearingDate: 'Wed Sep 21 2022',
  notifiedHearing: 'www.google.com',
  hearingDate: 'Wed Sep 21 2022',
  hearingTime: '02:30 PM',
  hearingLocation: 'Cabinet Building',
  committee: 'Senate',
  type: 'Decision Making',
  testifierContact: ['abc@gmail.com', 'def@gmail.com'],
  similar: [
    'orasdasem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet',
    'orem ipsdsdsum sddolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit amet',
  ],
  leadOfficePosition: 'What goes here?',
  testifier: 'Cara Tanimura',
  approvedTestimony: ['abcdefghij.pdf', 'abcdefghi.pdf', 'abcdefghsi.pdf'],
  monitoringReports: ['Report 1', 'Report 2'],
  hearingComments: ['Comment 1', 'Comment 2', 'Comment 3'],
  testimony: ['Testimony 1', 'Testimony 2', 'Testimony 3'],
  rationale:
    'orem ipsusdm dolasdor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
};
